<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Group;
use Symfony\Component\HttpFoundation\Response;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{

    public function saveNewGroup(Group $group)
    {
        $em = $this->getEntityManager();
        $em->persist($group);
        $em->flush();
        return new Response("Saved new group with id: ".$group->getId());
    }

    public function deleteGroup(Group $group)
    {
        $em = $this->getEntityManager();
        $id = $group->getId();
        $em->remove($group);
        $em->flush();
        return new Response("Removed group with id: ".$id);
    }
}
