<?php

namespace AppBundle\Repositories;

use AppBundle\Entity\Language;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends EntityRepository
{

    public function saveNewLanguage(Language $language){
        $em = $this->getEntityManager();
        $em->persist($language);
        $em->flush();
        return new Response("Saved new language with id: ".$language->getName());
    }

    public function deleteLanguage(Language $language)
    {
        $em = $this->getEntityManager();
        $id = $language->getName();
        $em->remove($language);
        $em->flush();
        return new Response("Removed language with id: ".$id);
    }
}
