<?php

namespace AppBundle\Repositories;

use AppBundle\Entity\Level;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * LevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelsRepository extends EntityRepository
{

    public function saveNewLevel(Level $level)
    {
        $em = $this->getEntityManager();
        $em->persist($level);
        $em->flush();
        return new Response("Saved new language with id: ".$level->getLevel());
    }

    public function deleteLevel(Level $level)
    {
        $em = $this->getEntityManager();
        $id = $level->getLevel();
        $em->remove($level);
        $em->flush();
        return new Response("Removed language with id: " . $id);
    }
}
