<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Group extends \AppBundle\Entity\Group implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'language', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'level', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'students', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'start_hour', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'length', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'weekday', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'capacity', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'created_at', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'updated_at');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'language', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'level', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'students', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'start_hour', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'length', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'weekday', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'capacity', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'created_at', '' . "\0" . 'AppBundle\\Entity\\Group' . "\0" . 'updated_at');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Group $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartHour($startHour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartHour', array($startHour));

        return parent::setStartHour($startHour);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartHour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartHour', array());

        return parent::getStartHour();
    }

    /**
     * {@inheritDoc}
     */
    public function setLength($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLength', array($length));

        return parent::setLength($length);
    }

    /**
     * {@inheritDoc}
     */
    public function getLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLength', array());

        return parent::getLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeekday($weekday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeekday', array($weekday));

        return parent::setWeekday($weekday);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeekday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeekday', array());

        return parent::getWeekday();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacity($capacity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacity', array($capacity));

        return parent::setCapacity($capacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacity', array());

        return parent::getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(\AppBundle\Entity\Language $language = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array());

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(\AppBundle\Entity\Level $level = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', array($level));

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', array());

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function addStudent(\AppBundle\Entity\Student $students)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStudent', array($students));

        return parent::addStudent($students);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStudent(\AppBundle\Entity\Student $students)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStudent', array($students));

        return parent::removeStudent($students);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudents', array());

        return parent::getStudents();
    }

}
